import TestRedirectBtn from '@/app/components/buttons/TestRedirectBtn';

export async function generateMetadata({ params }: { params: NextParams }) {
    const { slug } = await params;
    return {
        title: `Blog Page ${slug || ''}`,
        description: 'Generated by create next app',
    };
}
interface NextParams {
    slug: string[];
}
const BlogPage = async ({ params }: { params: NextParams }) => {
    // const { slug } = await params;

    return (
        <div>
            <h1>Blog Page</h1>
            <p>Slug: {JSON.stringify(await params)}</p>
            <TestRedirectBtn />
        </div>
    );
};

export default BlogPage;
